### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by fperez-eypscap** [DavidBriglio/cordova-clean#3]
Hi David, variables are not working for cordova-plugin-googlemaps.

Variables are set in config.xml:
plugin name="cordova-plugin-googlemaps" spec="^2.3.10">
        variable name="API_KEY_FOR_ANDROID" value="___" />
        variable name="API_KEY_FOR_IOS" value="___" />
        variable name="PLAY_SERVICES_VERSION" value="15.0.1" />
        variable name="ANDROID_SUPPORT_V4_VERSION" value="27.1.1" />
/plugin>
(Removed < to bypass Github sanitization)

They are also set in package.json:
"cordova-plugin-googlemaps": {
        "API_KEY_FOR_ANDROID": "___",
        "API_KEY_FOR_IOS": "___",
        "PLAY_SERVICES_VERSION": "15.0.1",
        "ANDROID_SUPPORT_V4_VERSION": "27.1.1"
      },

This is the log:
2018-08-09T18:02:56.9209213Z Installing "cordova-plugin-googlemaps" for android
2018-08-09T18:02:57.5520353Z Failed to install 'cordova-plugin-googlemaps': Error: Variable(s) missing: API_KEY_FOR_ANDROID
2018-08-09T18:02:57.5521245Z     at Object.mergeVariables (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\variable-merge.js:58:15)
2018-08-09T18:02:57.5521936Z     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:315:44
2018-08-09T18:02:57.5522435Z     at _fulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
2018-08-09T18:02:57.5522836Z     at self.promiseDispatch.done (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
2018-08-09T18:02:57.5523255Z     at Promise.promise.promiseDispatch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
2018-08-09T18:02:57.5523703Z     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:557:44
2018-08-09T18:02:57.5524070Z     at flush (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
2018-08-09T18:02:57.5524407Z     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2018-08-09T18:02:57.5524842Z     at process._tickCallback (internal/process/next_tick.js:180:9)
2018-08-09T18:02:57.5652227Z (node:10372) UnhandledPromiseRejectionWarning: Error: Variable(s) missing: API_KEY_FOR_ANDROID
2018-08-09T18:02:57.5652752Z     at Object.mergeVariables (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\variable-merge.js:58:15)
2018-08-09T18:02:57.5653144Z     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:315:44
2018-08-09T18:02:57.5653575Z     at _fulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
2018-08-09T18:02:57.5653989Z     at self.promiseDispatch.done (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
2018-08-09T18:02:57.5654407Z     at Promise.promise.promiseDispatch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
2018-08-09T18:02:57.5654791Z     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:557:44
2018-08-09T18:02:57.5655158Z     at flush (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
2018-08-09T18:02:57.5655496Z     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2018-08-09T18:02:57.5656110Z     at process._tickCallback (internal/process/next_tick.js:180:9)
2018-08-09T18:02:57.5657352Z (node:10372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2018-08-09T18:02:57.5660129Z (node:10372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-08-09T18:02:57.5824149Z 

Thanks.

**Comment by DavidBriglio** [comment]
I will look into this, thank you for the feedback!

**Comment by DavidBriglio** [comment]
This has been fixed in 1.3.2, please reopen this issue if you are still experiencing problems.

**Comment by fperez-eypscap** [comment]
Looks good, in my tests I haven't seen a problem yet. Thanks!
